apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prometheus-operator-serviceMonitor.yaml
- prometheus-serviceMonitorApiserver.yaml
- prometheus-serviceMonitorCoreDNS.yaml
- prometheus-serviceMonitorKubeControllerManager.yaml
- prometheus-serviceMonitorKubelet.yaml
- prometheus-serviceMonitorKubeScheduler.yaml
