apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: monitoring

# Defaultní namespace nemlže být přepsán pro všechny soubory, protože to koliduje s /base/services/monitoring/prometheus/RoleBindingList.yaml a 
# /base/services/monitoring/prometheus/RoleBinding.yaml
resources:
- ../../base/services/monitoring
- ConfigMap.yaml
- additional-scrape-configs.yaml
- Ingress.yaml

generators:
- SopsSecretGenerator.yaml