
image:
  repository: seyhello/memory-test
  pullPolicy: Always
  tag: latest

serviceAccount:
  # Specifies whether a service account should be created
  create: false


resources:
  limits:
    cpu: 200m
    memory: 800Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false