apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-actions-runner

resources:
  - ../../../base/services/github-actions/runner

patchesJson6902:
  - target:
      version: v1alpha1
      group: garo.tietoevry.com
      kind: GithubActionRunner
      name: runner-pool
    path: PatchesStrategicMerge.yaml

generators:
    - actions-runner.yaml