apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ConfigMap.yaml
- Deployment.yaml
- PodSecurityPolicy.yaml
- Role.yaml
- RoleBinding.yaml
- Service.yaml
- ServiceAccount.yaml