apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus-postgres-exporter
    chart: prometheus-postgres-exporter-2.3.0
    heritage: Helm
    release: prometheus-postgres-exporter
  name: prometheus-postgres-exporter
  namespace: monitoring