apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garo-leader-election-rolebinding
  namespace: garo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: garo-leader-election-role
subjects:
- kind: ServiceAccount
  name: garo-controller-manager
  namespace: garo-system