apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: garo-controller-manager-metrics-service
  namespace: garo-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: controller-manager